version: "3.8"
services:
  backend:
    build: ./backend
    container_name : backend
    networks:
      - mynet
  frontend:
    image: nginx:latest
    container_name: frontend
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - mynet

networks:
  mynet:
    name: mynet
    driver: bridge
